views/register.py
 # -*- coding: utf-8 -*-
from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, Blueprint, g
from wtforms import Form, StringField, TextAreaField, PasswordField, validators
from passlib.hash import sha256_crypt
from functools import wraps
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.datastructures import ImmutableMultiDict
from .db_connection import getDB
import logging
db = getDB()
from .auth import is_logged_in
import json
import traceback
from flask_mail import Mail, Message
import random
import sys
import re
import os
import pwd
import grp
from . import generic_functions
GF=generic_functions.GenericFunctions()
import app_config as cfg
# from flask import current_app as app
#from flask import current_app as app
bp = Blueprint('register', __name__, url_prefix='/register')


app=Flask(__name__)
app.config.update(dict(
    DEBUG = False,
    MAIL_SERVER=cfg.mail_server,
    MAIL_PORT=cfg.mail_port,
    MAIL_USERNAME=cfg.mail_username,
    MAIL_PASSWORD=cfg.mail_password,
    MAIL_USE_TLS=cfg.mail_use_tls,
    MAIL_USE_SSL=cfg.mail_use_ssl,
))
mail = Mail(app)

@bp.route('/new_company', methods=['GET','POST'])
@is_logged_in
def new_company():
    logging.info("entra a new company")
    form = RegisterNewCompany(request.form)
    logging.info(form['business_name'])

    if request.method == 'POST' and form.validate():
        logging.info("validated correctly")
        logging.info(request.form)
    else:
        logging.info("ocurrio un error")
        logging.info(form.errors)

    return render_template('home.html', form=form)

@bp.route('/dogrid', methods=['GET','POST'])
@is_logged_in
def dogrid():
    logging.info("entra a funcion dogrid")
    form = RegisterNewCompany(request.form)
    if request.method == 'POST'  and form.validate():
        logging.info("entra if")
        logging.info(request.form)
        return redirect(url_for(index))
    return render_template('home.html', form=form)

@bp.route('/saveNewCompany', methods=['GET','POST'])
@is_logged_in
def saveNewCompany():
    """
    Parameters:{business_name,name,address,phone}
    Description: Saves in DB new company
    """
    logging.info("entra a save company")
    response={}
    try:
        if request.method == 'POST':
            flag,dict=toDict(request.form,'post')
            if flag:
                logging.info("success: %s"%dict)
                for k,v in dict.iteritems():
                    if len(v.strip())==0:
                        response['success']=False
                        response['msg_response']='Existen campos vacíos, no es posible realizar el registro de la empresa.'
                        break
                if 'success' not in response:
                    new_folder=replaceString(dict['business_name'])[0:10]
                    company=db.insert('system.company',dict)
                    folder="%s_%s"%(new_folder,company['company_id'])
                    db.query("""
                        update system.company
                        set task_folder='%s'
                        where company_id=%s
                    """%(folder,company['company_id']))
                    logging.info(company)
                    # if not os.path.exists('/usr/local/arctic/tmp/%s'%folder):
                    #     os.makedirs('/usr/local/arctic/tmp/%s'%folder)
                    #     uid = pwd.getpwnam("pgarcia").pw_uid
                    #     gid = grp.getgrnam("pgarcia").gr_gid
                    #     path = '/usr/local/arctic/tmp/%s'%folder
                    if not os.path.exists('%s%s'%(cfg.task_path,folder)):
                        os.makedirs('%s%s'%(cfg.task_path,folder))
                        uid = pwd.getpwnam(cfg.admin_uid).pw_uid
                        gid = grp.getgrnam(cfg.admin_gid).gr_gid
                        path = '%s%s'%(cfg.task_path,folder)
                        os.chown(path, uid, gid)


                    response['success']=True
                    response['msg_response']='La empresa <b>%s</b> ha sido registrada.'%dict['name']

            else:
                response['success']=False
                response['msg_response']='Ocurrió un error al intentar obtener los datos del formulario, favor de intentarlo nuevamente.'

        else:
            logging.info("GET")

            response['success']=True
            response['msg_response']='La empresa ha sido registrada exitosamente.'

    except:
        response['success']=False
        response['msg_response']='Ocurrió un error al intentar registrar la empresa.'
        exc_info = sys.exc_info()
        app.logger.info(traceback.format_exc(exc_info))
    return json.dumps(response)

@bp.route('/getCompanies', methods=['GET','POST'])
@is_logged_in
def getCompanies():
    """
    Parameters:user_id
    Description:Gets list of registered companies.
    """
    response={}
    try:
        if request.method=='POST':
            flag,dict=toDict(request.form,'post')
            if flag:
                if dict['company_id']==-1:
                    companies=db.query("""
                        select
                            company_id,
                            business_name ||' - '|| name as name
                        from
                            system.company
                        order by name asc
                    """).dictresult()
                else:
                    companies=[]
                response['success']=True
                response['data']=companies
            else:
                response['success']=False
                response['msg_response']='Ocurrió un error, favor de intentarlo de nuevo.'
        else:
            response['success']=False
            response['msg_response']='Favor de iniciar sesión nuevamente.'

    except:
        response['success']=False
        response['msg_response']='Ocurrió un error, favor de intentarlo de nuevo.'
        exc_info = sys.exc_info()
        app.logger.info(traceback.format_exc(exc_info))
    return json.dumps(response)

@bp.route('/getUserType',methods=['GET','POST'])
@is_logged_in
def getUserType():
    response={}
    try:
        if request.method=='POST':
            flag,dict=toDict(request.form,'post')
            if flag:
                if dict['get']=='admin': #obtiene tipos de usuario para usuario administrador
                    user_type=db.query("""
                        select
                            user_type_id,
                            user_type
                        from
                            system.user_type
                        where
                            admin_privileges=True
                        and user_type <> 'root'
                    """).dictresult()
                elif dict['get']=='all':
                    user_type=db.query("""
                        select
                            user_type_id,
                            user_type
                        from
                            system.user_type
                        where
                            admin_privileges=False
                    """).dictresult()
                else:
                    user_type=[]
                response['success']=True
                response['data']=user_type
            else:
                response['success']=False
                response['msg_response']='Ocurrió un error, favor de intentarlo de nuevo.'
        else:
            response['success']=False
            response['msg_response']='Favor de iniciar sesión nuevamente.'
    except:
        response['success']=False
        response['msg_response']='Ocurrió un error, favor de intentarlo nuevamente.'
        exc_info = sys.exc_info()
        app.logger.info(traceback.format_exc(exc_info))
    return json.dumps(response)


# @bp.route('/sendMail', methods=['GET','POST'])
# def sendMail():
#     logging.info("entra mail")
#     msg=Message('Hello',sender='pgarcia@russellbedford.mx',recipients=['pazgarcia91@gmail.com'])
#     msg.body='Prueba mensaje flask'
#     mail.send(msg)
#     return 'Sent'

@bp.route('/createUser',methods=['GET','POST'])
@is_logged_in
def createUser():
    response={}
    try:
        if request.method=='POST':
            flag,dict=toDict(request.form,'post')

            if flag:
                if dict['user_id']==-1:
                    condition=""
                else:
                    condition=" and user_id<>%s"%dict['user_id']
                #check if login and mail already exists
                exist_email=db.query("""
                    select
                        count(*)
                    from
                        system.user
                    where
                        email='%s'
                    and company_id=%s %s
                """%(dict['email'],dict['company_id'],condition)).dictresult()
                exist_email[0]['count']=0 #bypass email validation
                if exist_email[0]['count']==0:
                    if dict['user_id']==-1:
                        exist_login=db.query("""
                            select
                                count(*)
                            from
                                system.user
                            where
                                login='%s'
                            --and company_id=%s
                        """%(dict['login'].lower(),dict['company_id'])).dictresult()
                        if exist_login[0]['count']==0:
                            passwd_success,passwd=generateRandomPassword(8)
                            if passwd_success:
                                dict['password']=generate_password_hash(passwd)
                                login=dict['login'].strip()
                                dict['login']=replaceString(login)
                                dict['login']=dict['login'].lower()
                                dict['name']=dict['name'].strip()

templates/modal/admin_users.html
<div class="modal fade" id="win_admin_users" data-keyboard="false" data-backdrop="static">
  <div class="vertical-alignment-helper">
      <div class="modal-dialog modal-lg vertical-align-center">
        <div class="modal-content">
          <div class="modal-header user-header header-win-title">
            <span>Administrar usuarios</span>
            <button type="button" class="btn-close-modal pull-right" data-dismiss="modal"><i class="fa fa-close"></i></button>
          </div>
          <div class="modal-body" style="width:100%;">
              <div class="alert alert-info alert-dismissible" id="alertAdminUsersWin" style="display:none;" role="alert">
                  <p>Ocurrió un error.</p>
                  <a href="#" class="close" data-hide="alert" aria-label="close">&times;</a>
              </div>
              <div class="content">
                  <div class="table-responsive">
                      <table class="table display" id="grdAdminUsers">
                        <thead>
                          <tr>
                            <th>Nombre</th>
                            <th>Usuario</th>
                            <th>Perfil</th>
                            <th>Correo</th>
                          </tr>
                        </thead>
                        <tbody></tbody>
                      </table>
                  </div>
              </div>

          </div>
          <div class="modal-footer user-footer">
            <button type="button" class="btn btn-light" data-toggle="tooltip" title="Agregar usuario" data-placement="bottom" id="btnNewUser">Nuevo <i class="fa fa-user-plus"></i></button>
            <button type="button" class="btn btn-light" data-toggle="tooltip" title="Editar usuario" data-placement="bottom" id="btnEditUser">Editar <i class="fa fa-pencil"></i></button>
            <button type="button" class="btn btn-light" data-toggle="tooltip" title="Deshabilitar usuario" data-placement="bottom" id="btnDisableUser">Deshabilitar <i class="fa fa-user-times"></i></button>
          </div>
        </div>
      </div>
  </div>
</div>

templates/modal/check_declined_task.html
<div class="modal fade" id="win_check_declined_task" data-keyboard="false" data-backdrop="static">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header user-header header-win-title">
                    <span>Revisar tarea declinada</span>
                    <button class="btn-close-modal pull-right" data-dismiss="modal" type="button"><i class="fa fa-close"></i></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-info alert-dismissible" id="alertCHDTask" style="display:none;" role="alert">
                        <p>Ocurrió un error</p>
                        <a href="#" class="close" data-hide="alert" aria-label="close">&times;</a>
                    </div>
                    <div class="jumbotron" style="margin:15px; padding:20px;">
                        <span id="CHDTtask_info"></span>
                    </div>
                    <form method="POST" id="frmCheckDeclinedTask" style="padding:8px;">
                        <div class="form-group row" >
                            <label for="CHDTassignee_id" class="col-md-3 col-form-label">Asignado a:</label>
                            <select class="form-control col-md-9" style="border-radius:5px;" name="assignee_id" id="CHDTassignee_id"></select>
                        </div>
                        <div class="form-group row">
                            <label for="CHDTdescription" class="col-md-3 col-form-label">Descripción:</label>
                            <textarea type="text" class="form-control col-md-9" id="CHDTdescription" name="description" style="width:100%;"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer user-footer">
                    <button class="btn btn-light" type="button" id="btnSaveCheckDeclinedTask" data-toggle="tooltip" title="Asignar tarea a auxiliar seleccionado y/o cambiar descripción">Enviar <i class="fa fa-calendar-check-o"></i></button>
                    <button class="btn btn-light" type="button" id="btnCancelDeclinedTask" data-toggle="tooltip" title="Cancelar tarea (ya no será asignada a ningún auxiliar)">Cancelar tarea <i class="fa fa-calendar-times-o"></i></button>
                    <button class="btn btn-light" type="button" id="btnCloseCheckDeclinedTask" data-toggle="tooltip" title="Salir sin realizar cambios">Salir <i class="fa fa-window-close"></i></button>
                </div>
            </div>
        </div>

    </div>

</div>

templates/modal/check_declined_task_supervisor.html
<div class="modal fade" id="win_check_declined_task_supervisor" data-keyboard="false" data-backdrop="static">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content" style="min-width:550px">
                <div class="modal-header user-header header-win-title">
                    <span>Revisar tarea declinada</span>
                    <button class="btn-close-modal pull-right" data-dismiss="modal" type="button"><i class="fa fa-close"></i></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-info alert-dismissible" id="alertCHDSUPTask" style="display:none;" role="alert">
                        <p>Ocurrió un error</p>
                        <a href="#" class="close" data-hide="alert" aria-label="close">&times;</a>
                    </div>
                    <div class="jumbotron" style="margin:15px; padding:20px;">
                        <span id="CHDSUPTtask_info"></span>
                    </div>
                    <form method="POST" id="frmCheckSupDeclinedTask" style="padding:8px;">
                        <div class="form-group row row-w-span">
                          <label for="CHDSUPdeadline" style="width:37%; padding-right:15px;padding-left:15px;" class="col-form-label">Fecha de vencimiento:</label>
                          <div style="width:63%; padding-right:15px;padding-left:15px;">
                             <input type="date" name="deadline" class="form-control" id="CHDSUPdeadline"/>
                          </div>
                        </div>
                        <div class="row">
                            <span style="width:37%;"></span>
                            <span class="error-msg" style="width:63%;" id="spnCHDSUPdeadline">Error</span>
                        </div>
                        <div class="form-group row row-w-span">
                          <label for="CHDSUPsupervisor_id" class="col-form-label" style="width:20%; padding-left:15px;">Supervisa:</label>
                          <div style="width:35%;padding-right:8px;">
                            <select id="CHDSUPsupervisor_id" class="form-control" placeholder="Supervisor" name="supervisor_id"></select>
                          </div>
                          <label for="CHDSUPsupervisor_deadline" style="width:13%;padding-left:8px;" class="col-form-label">Fecha:</label>
                          <div style="width:32%;padding-right:15px;">
                            <input type="date" class="form-control" id="CHDSUPsupervisor_deadline" name="supervisor_deadline"/>
                          </div>
                        </div>
                        <div class="row">
                            <span style="width:20%; padding-left:15px;"></span>
                            <span style="width:35%;padding-right:8px;" class="error-msg-row" id="spnCHDSUPsupervisor_id">Error</span>
                            <span style="width:13%;padding-left:8px;"></span>
                            <span style="width:32%;padding-right:15px;" class="error-msg-row" id="spnCHDSUPsupervisor_deadline">Error</span>
                        </div>
                        <div class="form-group row row-w-span">
                          <label for="CHDSUPassignee_id" style="width:20%; padding-left:15px;" class="col-form-label">Asignado a:</label>
                          <div style="width:35%; padding-right:8px;">
                            <select id="CHDSUPassignee_id" class="form-control" placeholder="Asignado a" name="assignee_id"></select>
                          </div>
                          <label for="CHDSUPassigee_deadline" class="col-form-label" style="width:13%;padding-left:8px;">Fecha:</label>
                          <div style="width:32%;padding-right:15px;">
                            <input type="date" id="CHDSUPassigee_deadline" class="form-control" name="assignee_deadline"/>
                          </div>
                        </div>
                        <div class="row">
                            <span style="width:20%; padding-left:15px;"></span>
                            <span style="width:35%; padding-right:8px;" class="error-msg-row" id="spnCHDSUPassignee_id">Error</span>
                            <span style="width:13%; padding-left:8px;"></span>
                            <span style="width:32%; padding-right:15px;" class="error-msg-row" id="spnCHDSUPassigee_deadline">Error</span>
                        </div>
                    </form>
                </div>
                <div class="modal-footer user-footer">
                    <button class="btn btn-light" type="button" id="btnSaveCheckDeclinedSupTask" data-toggle="tooltip" title="Asignar tarea a auxiliar seleccionado y/o cambiar descripción">Enviar <i class="fa fa-calendar-check-o"></i></button>
                    <button class="btn btn-light" type="button" id="btnCancelDeclinedSupTask" data-toggle="tooltip" title="Cancelar tarea (ya no será asignada a ningún auxiliar)">Cancelar tarea <i class="fa fa-calendar-times-o"></i></button>
                    <button class="btn btn-light" type="button" id="btnCloseCheckDeclinedSupTask" data-toggle="tooltip" title="Salir sin realizar cambios">Salir <i class="fa fa-window-close"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/modal/check_task.html
<div class="modal fade" id="win_check_task" data-keyboard="false" data-backdrop="static">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
             <div class="modal-content">
                 <div class="modal-header user-header header-win-title">
                     <span>Revisar tarea</span>
                     <button class="btn-close-modal pull-right" data-dismiss="modal" type="button"><i class="fa fa-close"></i></button>
                 </div>
                 <div class="modal-body">
                     <div class="alert alert-info alert-dismissible" id="alertCHTask" style="display:none;" role="alert">
                         <p>Ocurrió un error</p>
                         <a href="#" class="close" data-hide="alert" aria-label="close">&times;</a>
                     </div>
                     <div class="jumbotron" style="margin:15px; padding:20px;">
                         <span id="CHTtask_info"></span>
                     </div>
                     <div id="CHTevidences" style="margin:15px; padding:10px;">
                     </div>
                     <div class="row form-group" style="margin:1px;">
                         <label for="CHTcomments" class="col-md-3 col-form-label">Comentarios:</label>
                         <div class="col-md-9">
                             <textarea id="CHTcomments" type="text" name="comments" class="form-control" style="width:100%;" placeholder="Agregar comentario"></textarea>
                         </div>
                     </div>
                 </div>
                 <div class="modal-footer user-footer">
                     <button type="button" class="btn btn-light" id="btnCheckTaskComplete">Correcta <i class="fa fa-check-square-o"></i></button>
                     <button type="button" class="btn btn-light" id="btnCheckTaskIncomplete">Incompleta <i class="fa fa-remove"></i></button>
                     <button type="button" class="btn btn-light" id="btnCloseCheckTask">Salir <i class="fa fa-window-close"></i></button>
                 </div>
             </div>
        </div>
    </div>
</div>

templates/modal/decline_task.html
<div class="modal fade" id="win_decline_task" data-keyboard="false" data-backdrop="static">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header user-header header-win-title">
                    <span>Declinar tarea</span>
                    <button type="button" class="btn-close-modal pull-right" data-dismiss="modal"><i class="fa fa-close"></i></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-info alert-dismissible" id="alertDecTask" style="display:none;" role="alert">
                        <p>Ocurrió un error</p>
                        <a href="#" class="close" data-hide="alert" aria-label="close">&times;</a>
                    </div>
                    <div class="jumbotron" style="margin:15px; padding:20px;">
                        <span id="DecTinfo"></span>
                    </div>
                    <div class="row form-group row-w-span" style="margin:1px;">
                        <label for="DecTcomments" class="col-md-3 col-form-label">Comentarios:</label>
                        <div class="col-md-9">
                            <textarea id="DecTcomments" type="text" name="comments" class="form-control" style="width:100%;" placeholder="Agregar comentario"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <span class="col-md-3"></span>
                        <span class="col-md-9 error-msg" id="spnDecTdescription">Error</span>
                    </div>
                </div>
                <div class="modal-footer user-footer">
                    <button type="button" class="btn btn-light" id="btnDeclineTask">Declinar <i class="fa fa-minus-circle"></i></button>
                    <button type="button" class="btn btn-light" id="btnCloseDeclineTask">Salir <i class="fa fa-window-close"></i></button>
                </div>
            </div>
        </div>
    </div>

</div>

templates/modal/forgot_password.html
<div class="modal fade" id="win_forgot_password" data-keyboard="false" data-backdrop="static">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header password-win-header header-win-title">
                    <span>Recuperar contraseña</span>
                    <button type="button" class="btn-close-modal pull-right" data-dismiss="modal"><i class="fa fa-close"></i></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-info alert-dismissible" id="alertRecoverPassForm" style="display: none;" role="alert">
                        <p>Ocurrió un error.</p>
                        <a href="#" class="close" data-hide="alert" aria-label="close">&times;</a>
                    </div>
                    <form method="POST" id="frmRecoverPassword" style="margin:10px;">
                        <div class="form-group row row-w-span">
                            <label for="RPlogin" class="col-form-label col-md-2">Usuario:</label>
                            <div class="col-md-10">
                                <input type="text" id="RPlogin" name="login" placeholder="Usuario" class="form-control" data-toggle="tooltip" title="Ingrese el usuario con el que se encuentra registrado"/>
                            </div>
                        </div>
                        <div class="row">
                            <span class="col-md-2"></span>
                            <span class="col-md-10 error-msg" id="spnRPlogin">Error</span>
                        </div>
                        <div class="form-group row row-w-span">
                            <label for="RPemail" class="col-form-label col-md-2">Correo:</label>
                            <div class="col-md-10">
                                <input type="text" id="RPemail" name="email" placeholder="Correo electrónico" class="form-control" data-toggle="tooltip" title="El correo debe ser el mismo con el que se encuentra registrado"/>
                            </div>
                        </div>
                        <div class="row">
                            <span class="col-md-2"></span>
                            <span class="col-md-10 error-msg" id="spnRPemail">Error</span>
                        </div>
                    </form>
                </div>
                <div class="modal-footer password-win-header">
                    <button type="button" id="btnRecoverPassword" class="btn btn-light" data-toggle="tooltip" title="Recuperar contraseña">Enviar <i class="fa fa-send" style="color:#009900;"></i></button>
                    <button type="button" id="btnCloseForgotPassword" class="btn btn-light" data-toggle="tooltip" title="Salir">Salir <i class="fa fa-window-close"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/modal/new_company.html
<div class="modal fade" id="win_register_company" data-keyboard="false" data-backdrop="static">
  <div class="vertical-alignment-helper">
      <div class="modal-dialog vertical-align-center" style="overflow-y:initial !important">
        <div class="modal-content">
          <div class="modal-header user-header header-win-title">
              <span>Registro empresa</span>
              <button type="button" class="btn-close-modal" data-dismiss="modal"><i class="fa fa-close"></i></button>
          </div>
          <div class="modal-body">
            <!-- <form method="POST" action="{{ url_for('register.new_company')}}" id="frmRegisterCompany"> -->

            <div class="alert alert-info alert-dismissible" id="alertRCForm" style="display:none;" role="alert">
                <p>Ocurrió un error.</p>
                <a href="#" class="close" data-hide="alert" aria-label="close">&times;</a>
            </div>
            <form method="POST" action="" id="frmRegisterCompany">
                <div class="form-group">
                    <label for="RCbusiness_name">Razón Social:</label>
                    <input id="RCbusiness_name" name="business_name" type="text" value="" class="form-control">
                    <span class="error-msg" id="spnRCbusiness_name">Error</span>
                </div>
                <div class="form-group">
                    <label for="RCname">Nombre de la empresa:</label>
                    <input id="RCname" name="name" type="text" value="" class="form-control">
                    <span class="error-msg" id="spnRCname">Error</span>
                </div>
                <div class="form-group">
                    <label for="RCaddress">Dirección:</label>
                    <input id="RCaddress" name="address" type="text" value="" class="form-control">
                    <span class="error-msg" id="spnRCaddress">Error</span>
                </div>
                <div class="form-group">
                    <label for="RCphone">Teléfono:</label>
                    <input id="RCphone" name="phone" type="text" value="" class="form-control">
                    <span class="error-msg" id="spnRCphone">Error</span>
                </div>
            </form>
          </div>
          <div class="modal-footer user-footer">
              <button type="button" class="btn btn-light" id="btnSaveRegisterCompany">Guardar <i class="fa fa-save"></i></button>
              <button type="button" class="btn btn-light" id="btnCloseRegisterCompany">Salir <i class="fa fa-window-close"></i></button>
          </div>
        </div>
      </div>
  </div>
</div>